"""Feature ablations: drop one feature group at a time and measure the change.

    python -m src.ablate                        # LightGBM (units) and CatBoost (raw)
    python -m src.ablate --models lightgbm_units --repeats 1

Every run uses the same folds and seed as the full model, so differences are
paired. Rule of thumb from the repeated-CV standard error: a change under
about 1.5 RMSE is not evidence either way.

Also compares the target transforms on each model, since that is the other
modelling choice that needs evidence. Writes reports/ablations.md and
outputs/ablations.json.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import replace
from pathlib import Path

from src.config import DATA_RAW, OUTPUTS, REPORTS, SEED
from src.cv import prepare, run_cv
from src.data import load_raw
from src.features import FEATURE_GROUPS
from src.models import SPECS_BY_NAME, library_status, load_tuned
from src.targets import TRANSFORMS

MODELS = ["lightgbm_units", "catboost_raw"]
TARGETS = ["raw", "sqrt", "log1p", "units", "units_unweighted"]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--models", nargs="+", default=MODELS, choices=sorted(SPECS_BY_NAME))
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument("--skip-targets", action="store_true")
    parser.add_argument("--data", type=Path, default=DATA_RAW)
    args = parser.parse_args()

    train_raw, test_raw = load_raw(args.data)
    results = {"features": [], "targets": []}

    for name in args.models:
        spec = SPECS_BY_NAME[name]
        if problem := library_status(spec.library):
            print(f"skipped {name}: {problem}")
            continue
        tuned = load_tuned(name)
        full = run_cv(spec, train_raw, test_raw, prepare(train_raw, test_raw, matrices=[spec.matrix]),
                      tuned, n_repeats=args.repeats, seed=SEED)
        print(f"\n{name}: all features {full.oof_rmse:.2f}")
        results["features"].append({"model": name, "dropped": "(none)", "rmse": round(full.oof_rmse, 2), "delta": 0.0})

        for group, columns in FEATURE_GROUPS.items():
            prepared = prepare(train_raw, test_raw, drop=set(columns), matrices=[spec.matrix])
            r = run_cv(spec, train_raw, test_raw, prepared, tuned, n_repeats=args.repeats, seed=SEED)
            delta = r.oof_rmse - full.oof_rmse
            results["features"].append({"model": name, "dropped": group, "columns": columns,
                                        "rmse": round(r.oof_rmse, 2), "delta": round(delta, 2)})
            print(f"  drop {group:18s} {r.oof_rmse:8.2f}   {delta:+.2f}")

        if not args.skip_targets:
            prepared = prepare(train_raw, test_raw, matrices=[spec.matrix])
            for target in TARGETS:
                r = run_cv(replace(spec, target=target), train_raw, test_raw, prepared, tuned,
                           n_repeats=args.repeats, seed=SEED)
                results["targets"].append({"model": name, "target": target, "rmse": round(r.oof_rmse, 2),
                                           "negative_prediction_share": round(r.negative_share, 4)})
                print(f"  target {target:17s} {r.oof_rmse:8.2f}   negatives {r.negative_share:.2%}")

    OUTPUTS.mkdir(exist_ok=True)
    (OUTPUTS / "ablations.json").write_text(json.dumps(results, indent=2))

    lines = ["# Ablations", "", "Generated by `python -m src.ablate`. Paired 5-fold × 3 CV, RMSE on the sales "
             "scale. Positive delta means dropping the group made the model worse. Differences under about "
             "1.5 are within noise.", "", "## Feature groups", "", "| Model | Dropped | RMSE | Delta |", "|---|---|---|---|"]
    for r in results["features"]:
        lines.append(f"| {r['model']} | {r['dropped']} | {r['rmse']:.2f} | {r['delta']:+.2f} |")
    if results["targets"]:
        lines += ["", "## Target transforms", "", "| Model | Target | RMSE | Negative predictions |", "|---|---|---|---|"]
        for r in results["targets"]:
            lines.append(f"| {r['model']} | {r['target']} | {r['rmse']:.2f} | {r['negative_prediction_share']:.2%} |")
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "ablations.md").write_text("\n".join(lines) + "\n")
    print(f"\nWrote {REPORTS / 'ablations.md'}")


if __name__ == "__main__":
    main()
