"""Assemble reports/experiments.md from the saved results.

    python -m src.report

Reads outputs/cv_results.json (src/train.py), outputs/params/*.study.json
(src/tune.py), outputs/validation.json and outputs/ablations.json when they
exist, plus the residual correlations between the saved out-of-fold
predictions. Nothing here is typed by hand, so the table can't drift from
the runs.
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

from src.config import OUTPUTS, REPORTS, TARGET
from src.data import load_raw


def residual_correlations(names: list[str]) -> pd.DataFrame:
    train, _ = load_raw()
    y = train[TARGET].to_numpy(dtype=float)
    residuals = {n: y - np.load(OUTPUTS / "oof" / f"{n}.npy") for n in names}
    return pd.DataFrame(residuals).corr()


def main() -> None:
    cv = json.loads((OUTPUTS / "cv_results.json").read_text())
    lines = [
        "# Experiments", "",
        "Generated by `python -m src.report` from the saved results. RMSE on the sales scale; lower is better.",
        "", "## Cross-validated models", "",
        f"{cv['cv']['n_splits']}-fold × {cv['cv']['n_repeats']} repeats, stratified by store, seed {cv['cv']['seed']}. "
        f"Baseline (always predict the mean): **{cv['baseline_rmse']:,.2f}**. "
        "Preprocessing is fitted inside each training fold and early-stopping split. Historical runs without cv.fold_fit=true used global preprocessing.", "",
        "| Model | OOF RMSE | Fold mean ± std | Rounds | Seconds |", "|---|---|---|---|---|",
    ]
    for m in cv["models"]:
        rounds = m.get("best_iterations_mean", "")
        lines.append(f"| {m['model']} | {m['oof_rmse']:.2f} | {m['fold_rmse_mean']:.1f} ± {m['fold_rmse_std']:.1f} | {rounds} | {m['seconds']} |")
    if cv.get("skipped"):
        lines += ["", "Skipped: " + "; ".join(f"{k} ({v})" for k, v in cv["skipped"].items())]

    b = cv["blend"]
    lines += [
        "", "## Blend", "",
        f"Non-negative weights summing to one, fitted on out-of-fold predictions: {b['weights']}.", "",
        f"- In-sample blend RMSE (weights fitted and scored on the same rows, optimistic): {b['oof_rmse']:.2f}",
        f"- Second-stage OOF-row crossfit RMSE (not fully nested; selection bias remains): **{b.get('row_crossfit_rmse', b.get('honest_cv_rmse')):.2f}**",
        f"- Best single model: {cv['models'][0]['model']} at {cv['models'][0]['oof_rmse']:.2f}",
        f"- Recommended submission: `{cv['submissions']['recommended']}`",
    ]

    top = [m["model"] for m in cv["models"][:8]]
    corr = residual_correlations(top)
    lines += ["", "### Residual correlations (top 8 models)", "",
              "Blending helps when residuals are weakly correlated; values near 1 mean the models make the same mistakes.", "",
              "| | " + " | ".join(top) + " |", "|---|" + "---|" * len(top)]
    for n in top:
        lines.append(f"| {n} | " + " | ".join(f"{corr.loc[n, m]:.3f}" for m in top) + " |")

    studies = sorted(OUTPUTS.glob("params/*.study.json"))
    if studies:
        lines += ["", "## Hyperparameter search (Optuna; search scores, selection-biased)", "", "| Model | Default params RMSE | Tuned RMSE | Trials | CV during search |", "|---|---|---|---|---|"]
        for path in studies:
            s = json.loads(path.read_text())
            name = path.name.replace(".study.json", "")
            lines.append(f"| {name} | {s['default_params_rmse']:.2f} | {s['cv_rmse']:.2f} | {s['trials']} | {s['splits']}-fold × {s['repeats']} |")

    for label, filename in (("Validation study", "validation.md"), ("Ablations", "ablations.md")):
        if (REPORTS / filename).exists():
            lines += ["", f"## {label}", "", f"See [{filename}]({filename})."]

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "experiments.md").write_text("\n".join(lines) + "\n")
    print(f"Wrote {REPORTS / 'experiments.md'}")


if __name__ == "__main__":
    main()
