"""Validation study: is the cross-validation trustworthy, and what do the
preprocessing choices cost?

    python -m src.validate

Answers, for a few representative models:

1. Baseline: RMSE of always predicting the training mean.
2. Holdout vs repeated stratified K-fold vs grouped-by-product K-fold.
   Grouped folds hold out whole products, a scenario the competition never
   poses (every test product appears in train), so they measure how much a
   model leans on product identity rather than how it will score.
3. Preprocessing fit on train and test features together (transductive,
   label-free) vs refit inside every fold on the training rows only.
4. Clipping negative predictions: how many there are and what it changes.

Writes reports/validation.md and outputs/validation.json.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.config import DATA_RAW, OUTPUTS, REPORTS, SEED, TARGET
from src.cv import prepare, rmse, run_cv
from src.data import load_raw
from src.models import SPECS_BY_NAME, library_status, load_tuned

MODELS = ["store_rate_popularity", "ridge_interactions", "lightgbm_units", "catboost_raw"]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--models", nargs="+", default=MODELS, choices=sorted(SPECS_BY_NAME))
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument("--data", type=Path, default=DATA_RAW)
    args = parser.parse_args()

    train_raw, test_raw = load_raw(args.data)
    y = train_raw[TARGET].to_numpy(dtype=float)
    baseline = rmse(y, np.full_like(y, y.mean()))
    prepared = prepare(train_raw, test_raw)
    prepared_train_only = prepare(train_raw, test_raw, use_test_features=False)

    rows = []
    for name in args.models:
        spec = SPECS_BY_NAME[name]
        if problem := library_status(spec.library):
            print(f"skipped {name}: {problem}")
            continue
        tuned = load_tuned(name)
        runs = {
            "holdout 80/20": dict(scheme="holdout"),
            "5-fold x 3 stratified": dict(scheme="stratified", n_repeats=args.repeats),
            "5-fold x 3 grouped by product": dict(scheme="grouped", n_repeats=args.repeats),
            "5-fold x 3, preprocessing fit on train only": dict(prepared=prepared_train_only, n_repeats=args.repeats),
            "5-fold x 3, preprocessing refit in fold": dict(fold_fit=True, n_repeats=args.repeats),
        }
        for label, kwargs in runs.items():
            kwargs.setdefault("prepared", prepared)
            r = run_cv(spec, train_raw, test_raw, params=tuned, seed=SEED, **kwargs)
            rows.append({
                "model": name, "validation": label, **{k: v for k, v in r.summary().items() if k not in ("model", "scheme")},
                "negative_prediction_share": round(r.negative_share, 4),
            })
            print(f"  {name:24s} {label:46s} RMSE {r.oof_rmse:8.2f}  folds ±{np.std(r.fold_rmse):5.1f}  "
                  f"neg {r.negative_share:.2%}  {r.seconds:.0f}s")

    table = pd.DataFrame(rows)
    OUTPUTS.mkdir(exist_ok=True)
    (OUTPUTS / "validation.json").write_text(json.dumps({"baseline_rmse": round(baseline, 2), "runs": rows}, indent=2))

    lines = [
        "# Validation study", "",
        "Generated by `python -m src.validate`. RMSE on the sales scale; lower is better.", "",
        f"Baseline, always predicting the training mean: **{baseline:,.2f}**.", "",
        "| Model | Validation | RMSE | Fold mean ± std | Folds | Negative predictions | Seconds |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| {r['model']} | {r['validation']} | {r['oof_rmse']:.2f} | {r['fold_rmse_mean']:.1f} ± {r['fold_rmse_std']:.1f} "
                     f"| {r['n_folds']} | {r['negative_prediction_share']:.2%} | {r['seconds']} |")
    lines += [
        "",
        "## How to read it",
        "",
        "- **Holdout vs K-fold**: a single 20% split has a standard error of roughly the fold std, so it "
        "can rank two close models the wrong way; the repeated K-fold number is the one to trust.",
        "- **Grouped by product**: validation products are unseen. Every test product appears in train, so "
        "this is not the competition's scenario; it shows how much each model relies on product identity.",
        "- **Preprocessing fit on train only / refit in fold**: the default fits imputation and aggregate "
        "features on train and test *features* together (no sales). If these rows match the default, "
        "that choice is harmless.",
        "- **Negative predictions**: predictions are clipped at zero, which can only reduce squared error. "
        "The share tells how often it matters.",
    ]
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "validation.md").write_text("\n".join(lines) + "\n")
    print(f"\nWrote {REPORTS / 'validation.md'}")


if __name__ == "__main__":
    main()
